shellEmulator: true
trustPolicy: no-downgrade

packages: []

catalog:
  '@types/micromatch': ^4.0.10
  micromatch: ^4.0.8

catalogs:
  build:
    tsdown: ^0.18.4

  cli:
    '@vscode/vsce': ^3.7.1
    pncat: ^0.7.8

  conflicts_cli_h19_11_0:
    taze: ^19.11.0

  conflicts_lint_h9_39_4:
    eslint: ^9.39.4

  conflicts_types_h25_5_2:
    '@types/node': ^25.5.2

  conflicts_utils_h4_6_2:
    comment-json: ^4.6.2

  conflicts_vscode_h1_6_0:
    vscode-ext-gen: ^1.6.0

  lint:
    '@antfu/eslint-config': ^6.7.3

  network:
    ofetch: ^1.5.1

  tsc:
    typescript: ^5.9.3

  vscode:
    reactive-vscode: ^0.4.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - '@vscode/vsce-sign'
  - keytar
